# 论文契约端到端测试：生成契约（强制攻击）→ 反谄媚回应 → 局限/待解决 → 确认锁定 → 按契约起草 → 导出
import asyncio, sys, os
from playwright.async_api import async_playwright
HERE=os.path.dirname(os.path.abspath(__file__))
B=sys.argv[1] if len(sys.argv)>1 else "http://127.0.0.1:18824"
OUT=os.path.join(HERE,"out","contract")
def one(s): return s.replace("\n"," | ")
async def api(pg, method, path, body=None):
    return await pg.evaluate("""async ([m,p,b])=>{const r=await fetch(p,{method:m,headers:{'Content-Type':'application/json','X-KY':'1'},body:b?JSON.stringify(b):undefined});return [r.status, await r.json().catch(()=>null)]}""",[method,path,body])
async def main():
    os.makedirs(OUT, exist_ok=True)
    async with async_playwright() as p:
        b=await p.chromium.launch(); errs=[]
        ctx=await b.new_context(viewport={"width":1360,"height":900})
        pg=await ctx.new_page(); pg.on("pageerror", lambda e: errs.append(str(e)))
        pg.on("response", lambda r: errs.append(f"{r.status} {r.url}") if r.status>=500 else None)
        pg.on("dialog", lambda d: asyncio.ensure_future(d.accept()))
        await pg.goto(B)
        await api(pg,"POST","/api/setup",{"org_name":"智能感知课题组","username":"admin","name":"陈老师","password":"teach123"})
        await api(pg,"POST","/api/login",{"username":"admin","password":"teach123"})
        st,m=await api(pg,"POST","/api/models",{"name":"DeepSeek","base_url":"http://127.0.0.1:11434/v1","model":"deepseek-v4-pro","key":"k"})
        mid=m["mine"][0]["id"]; await api(pg,"POST",f"/api/models/{mid}/check"); await api(pg,"POST",f"/api/models/{mid}/activate",{"active":True})
        await pg.evaluate("""async (t)=>{const fd=new FormData();fd.append('file',new File([t],'attention.md'));await fetch('/api/materials',{method:'POST',headers:{'X-KY':'1'},body:fd})}""", open(os.path.join(HERE,"paper_a.md"),encoding="utf-8").read())
        await pg.goto(B+"/#/writing/contract"); await pg.reload(); await pg.wait_for_selector("form[data-submit=ctPlan]")
        await pg.fill("form[data-submit=ctPlan] input[name=title]","短视频与注意力")
        await pg.fill("form[data-submit=ctPlan] textarea[name=idea]","我想研究短视频使用时长会不会让大学生注意力变差。\n准备记录 60 名学生两周的屏幕使用时间，并做注意力测验。\n两周无推荐流干预后，干预组专注时长从 18 分钟增加到 24 分钟。")
        await pg.wait_for_selector("#ctMats input[name=mids]"); await pg.check("#ctMats input[name=mids] >> nth=0")
        await pg.click("form[data-submit=ctPlan] button[type=submit]")
        await pg.wait_for_selector("#ctView .ctatk", timeout=40000)
        atks=await pg.locator(".ctatk").all_inner_texts()
        print("ATTACKS:", len(atks), [one(a)[:40] for a in atks])
        print("PROBLEMS:", one(await pg.inner_text(".ctgate .msg.err"))[:160])
        await pg.screenshot(path=f"{OUT}/contract.png", full_page=True)
        async def aid(word):
            for i in range(await pg.locator(".ctatk").count()):
                t=await pg.locator(".ctatk").nth(i).inner_text()
                if word in t: return await pg.locator(".ctatk").nth(i).get_attribute("id")
        async def rebut(word, text):
            i=await aid(word); n0=await pg.locator(f"#{i} .ctturn.ai").count()
            await pg.fill(f"#{i} .ctReply", text); await pg.click(f"#{i} button[data-act=ctRebut]")
            await pg.wait_for_function("([s,n])=>document.querySelectorAll(s).length>n",arg=[f"#{i} .ctturn.ai",n0],timeout=30000); await pg.wait_for_timeout(300)
            return one(await pg.inner_text(f"#{i}"))
        # 反谄媚：只是坚持 → 不让步
        t=await rebut("相关性","我觉得这就是因果关系，大家都这么认为。")
        print("WEAK REBUT:", "按规则不让步" in t, "未处理" in t, "坚持质疑" in t)
        # 有证据 → 让步
        t=await rebut("相关性","我们做了随机分组：干预组 32 人、对照组 30 人，干预前两组注意力得分没有差异。")
        print("STRONG REBUT:", "审稿人已接受" in t, "认可的证据" in t)
        t=await rebut("故意表现","专注时长用软件自动记录，学生不知道具体指标（盲测），记录了 14 天共 840 条数据。")
        print("MEASURE REBUT:", "审稿人已接受" in t)
        i=await aid("睡眠"); await pg.fill(f"#{i} .ctReply","没有测量睡眠，无法完全排除睡眠的影响。"); await pg.click(f"#{i} button[data-act=ctResolve][data-s=limitation]"); await pg.wait_for_timeout(500)
        i=await aid("推广"); await pg.click(f"#{i} button[data-act=ctResolve][data-s=open]"); await pg.wait_for_timeout(500)
        i=await aid("反过来"); await pg.click(f"#{i} button[data-act=ctResolve][data-s=limitation]"); await pg.wait_for_timeout(500)
        print("GATE:", one(await pg.inner_text(".ctgate"))[:120])
        await pg.click("button[data-act=ctConfirm]"); await pg.wait_for_selector(".ctcard.locked")
        print("LOCKED:", await pg.inner_text(".ctcard .tag.ok"), "| inputs disabled:", await pg.locator("#ctQ[disabled]").count())
        await pg.screenshot(path=f"{OUT}/locked.png")
        r=await pg.evaluate("async ()=>{const id=document.querySelector('a[href^=\"/api/contracts.md\"]').getAttribute('href');const t=await (await fetch(id)).text();return t}")
        print("MD:", "已确认 v1" in r, "写进局限" in r, "待解决" in r, "什么情况下不成立" in r)
        # 按契约起草
        await pg.click("button[data-act=ctDraft]"); await pg.wait_for_selector("#dfContract")
        await pg.wait_for_timeout(500)
        print("DRAFT CONTRACT SELECTED:", await pg.eval_on_selector("#dfContract","e=>e.selectedOptions[0].textContent"), "| idea required:", await pg.eval_on_selector("textarea[name=idea]","e=>e.required"))
        await pg.select_option("#dfSection","引言")
        await pg.click("form[data-submit=dfPlan] button[type=submit]"); await pg.wait_for_selector("#dfClaims .dfclaim", timeout=30000)
        print("PLAN:", one(await pg.inner_text("#dfPlanBox .msg.info"))[:80])
        await pg.screenshot(path=f"{OUT}/draft_by_contract.png")
        # 起草 → 导出前必须先对照契约检查 → 逐项确认 → 下载
        await pg.click("button[data-act=dfWrite]"); await pg.wait_for_selector("#dfDraftBox .dftext", timeout=30000)
        await pg.click("button[data-act=dfCopy]"); await pg.wait_for_selector("#modal:not(.hide)")
        print("COPY BEFORE DRIFT:", one(await pg.inner_text("#modalBody"))[:40])
        await pg.click("#modalBody button[data-act=closeModal]")
        await pg.click("button[data-act=dfDrift]"); await pg.wait_for_selector("text=重新对照契约检查", timeout=30000)
        drift=await pg.inner_text("#dfDraftBox")
        print("DRIFT:", "超出契约的新主张" in drift, "S99" not in drift and "编造的句子编号" not in drift, "因果说法" in drift)
        await pg.screenshot(path=f"{OUT}/drift.png", full_page=True)
        await pg.click("button[data-act=dfDocx]"); await pg.wait_for_selector("form[data-submit=dfConfirm]")
        n=await pg.locator("form[data-submit=dfConfirm] input[type=checkbox]").count()
        await pg.screenshot(path=f"{OUT}/confirm.png")
        await pg.click("form[data-submit=dfConfirm] button[type=submit]"); await pg.wait_for_timeout(400)
        print("CONFIRM ITEMS:", n, "| unchecked blocked:", await pg.locator("form[data-submit=dfConfirm]").count()==1)
        for k in range(n): await pg.check(f"form[data-submit=dfConfirm] input[type=checkbox] >> nth={k}")
        async with pg.expect_download() as dl:
            await pg.click("form[data-submit=dfConfirm] button[type=submit]")
        d=await dl.value; path=await d.path()
        print("DOCX DOWNLOADED:", d.suggested_filename, os.path.getsize(path)>2000, "| confirmed note:", "已在" in await pg.inner_text("#dfDraftBox"))
        # 全文组装：再按契约起草摘要和结论（接口），然后在界面上拼装、检查、确认、导出
        st,cts=await api(pg,"GET","/api/contracts"); ctid=cts[0]["id"]
        for sec in ["摘要","结论"]:
            st,pl=await api(pg,"POST","/api/writing/plan",{"contract_id":ctid,"section":sec,"idea":"","results":"","material_ids":[]})
            did=pl["draft"]["id"]
            st,dr=await api(pg,"POST","/api/writing/draft",{"id":did,"claims":pl["draft"]["claims"],"length":""})
            await api(pg,"POST","/api/writing/drift",{"id":did})
            st,cf=await api(pg,"POST","/api/writing/confirm",{"id":did,"checks":{"facts":True,"ai":True,"gaps":True,"issues":True}})
            print("SECTION", sec, st)
        await pg.click("#wrTabs button[data-t=full]"); await pg.wait_for_selector("form[data-submit=fpNew]")
        await pg.select_option("form[data-submit=fpNew] select[name=contract]", index=1)
        await pg.click("form[data-submit=fpNew] button[type=submit]"); await pg.wait_for_selector(".fpcard")
        picked=await pg.eval_on_selector_all(".fprow select","els=>els.map(e=>e.selectedOptions[0]?e.selectedOptions[0].textContent:'')")
        print("FULL PICKED:", [x[:12] for x in picked])
        print("FULL ERRORS BEFORE:", [one(x)[:40] for x in await pg.locator(".fpcard .writem.lv-error").all_inner_texts()], "| export disabled:", await pg.locator("button[data-act=fpDocx][disabled]").count()==1)
        await pg.fill(".fpmeta input[name=keywords]","短视频；注意力；大学生"); await pg.press(".fpmeta input[name=keywords]","Tab")
        await pg.wait_for_selector("button[data-act=fpDocx]:not([disabled])", timeout=10000)
        print("FULL ERRORS AFTER:", await pg.locator(".fpcard .writem.lv-error").count(), "| warns:", await pg.locator(".fpcard .writem.lv-warn").count())
        await pg.click(".fpprev summary"); await pg.wait_for_timeout(200)
        print("FULL PREVIEW:", one(await pg.inner_text(".fpdoc"))[:120])
        await pg.screenshot(path=f"{OUT}/full_paper.png", full_page=True)
        await pg.click("button[data-act=fpDocx]"); await pg.wait_for_selector("form[data-submit=fpConfirm]")
        n=await pg.locator("form[data-submit=fpConfirm] input[type=checkbox]").count()
        for k in range(n): await pg.check(f"form[data-submit=fpConfirm] input[type=checkbox] >> nth={k}")
        async with pg.expect_download() as dl:
            await pg.click("form[data-submit=fpConfirm] button[type=submit]")
        d=await dl.value; path=await d.path()
        import docx as _docx
        fd=_docx.Document(path); txt="\n".join(x.text for x in fd.paragraphs)
        print("FULL DOCX:", d.suggested_filename, "| confirm items", n, "| has 关键词:", "关键词：短视频；注意力；大学生" in txt, "| sections:", sum(1 for h in ["摘要","1 引言","2 结论"] if h in txt), "| AI note:", "AI 辅助起草的全文" in txt)
        async with pg.expect_download() as dl:
            await pg.click("button[data-act=fpTex]")
        d=await dl.value; tex=open(await d.path(),encoding="utf-8").read()
        print("FULL TEX:", d.suggested_filename, "\\begin{abstract}" in tex, "\\section{引言}" in tex)
        # 请老师审阅：另一位老师查看（只读）并退回
        await api(pg,"POST","/api/users",{"username":"li","name":"李老师","role":"teacher","password":"teach456"})
        await pg.goto(B+"/#/writing/contract"); await pg.wait_for_selector("#ctList a[data-act=ctOpen]")
        await pg.click("#ctList a[data-act=ctOpen] >> nth=0"); await pg.wait_for_selector(".ctcard.locked")
        await pg.click("button[data-act=ctAskReview]"); await pg.wait_for_selector("form[data-submit=ctAskReviewGo]")
        await pg.fill("form[data-submit=ctAskReviewGo] textarea[name=note]","请重点看因果那条")
        await pg.click("form[data-submit=ctAskReviewGo] button[type=submit]"); await pg.wait_for_selector(".ctreview .tag.warn")
        print("REQUESTED:", one(await pg.inner_text(".ctreview"))[:60])
        tctx=await b.new_context(viewport={"width":1360,"height":900}); tp=await tctx.new_page(); tp.on("pageerror", lambda e: errs.append("T:"+str(e)))
        tp.on("dialog", lambda d: asyncio.ensure_future(d.accept()))
        await tp.goto(B); await api(tp,"POST","/api/login",{"username":"li","password":"teach456"}); await tp.goto(B+"/#/"); await tp.reload()
        await tp.wait_for_selector("a[data-act=homeContract]")
        print("TEACHER TODO:", one(await tp.inner_text("a[data-act=homeContract]")))
        await tp.click("a[data-act=homeContract]"); await tp.wait_for_selector("#ctRvText")
        print("TEACHER VIEW: readonly", await tp.locator("#ctQ[disabled]").count()==1, "| no owner buttons", await tp.locator("button[data-act=ctUnlock],button[data-act=ctDel],button[data-act=ctSave]").count()==0,
              "| list", await tp.locator("#ctReviewBox .rsrow").count())
        await tp.fill("#ctRvText","因果那条只有前后测，建议加对照组的基线描述。"); await tp.click("button[data-act=ctReview][data-d=return]")
        await tp.wait_for_selector(".ctreview .tag.bad"); await tp.screenshot(path=f"{OUT}/teacher_review.png", full_page=True)
        await tctx.close()
        await pg.goto(B+"/#/"); await pg.wait_for_selector(".homegrid")
        print("OWNER TODO:", one(await pg.inner_text(".homegrid"))[:0] + str("论文契约被老师退回" in await pg.inner_text(".homegrid")))
        await pg.goto(B+"/#/writing/contract"); await pg.wait_for_selector("#ctList a[data-act=ctOpen]")
        print("OWNER LIST:", "老师退回修改" in await pg.inner_text("#ctList"))
        # 解锁后草稿提示
        await pg.click("#ctList a[data-act=ctOpen] >> nth=0"); await pg.wait_for_selector(".ctcard.locked")
        print("OWNER SEES REVIEW:", "对照组的基线描述" in await pg.inner_text(".ctreview"))
        await pg.click("button[data-act=ctUnlock]"); await pg.wait_for_selector(".ctcard:not(.locked) button[data-act=ctSave]")
        print("UNLOCKED ok")
        # 深色 + 手机截图
        await pg.emulate_media(color_scheme="dark"); await pg.wait_for_timeout(300); await pg.screenshot(path=f"{OUT}/contract_dark.png")
        mc=await b.new_context(viewport={"width":390,"height":844},device_scale_factor=2, storage_state=await ctx.storage_state()); mp=await mc.new_page(); mp.on("pageerror", lambda e: errs.append("M:"+str(e)))
        await mp.goto(B+"/#/writing/contract"); await mp.wait_for_selector("#ctList a[data-act=ctOpen]"); await mp.click("#ctList a[data-act=ctOpen] >> nth=0"); await mp.wait_for_selector(".ctatk"); await mp.wait_for_timeout(500)
        await mp.screenshot(path=f"{OUT}/m_contract.png")
        print("ERRORS:", errs); await b.close()
asyncio.run(main())
